### ISSUE TITLE
abstracts need to have <para>s in docinfo.xml

### ISSUE THREAD

**Issue by soulcharmer** [jhradilek/check-links#3]
docinfo.xml

< abstract > {Abstract}< / abstract >

Should be: 

< abstract >
  < para >
    {Abstract}
  < / para >
< / abstract >

Otherwise ccutil is unable to parse abstracts for localization.

Originally reported by Ludek - we tested that adding the tags works.

Thank you for considering it

**Comment by jhradilek** [comment]
Hi @soulcharmer , thank you for opening the request. Could you please double-check the formatting of your report to ensure that everything that should be displayed is displayed? I have a feeling that there are missing `<para>` tags somewhere and it's difficult for me to guess what the expected content is.

**Comment by jhradilek** [comment]
Fixed in commit 9a71e62. @soulcharmer, would you mind verifying that the new version works as requested?
