### ISSUE TITLE
comparing-rhel-8-to-rhel-7 renamed

### ISSUE THREAD

**Issue by lspackova** [jhradilek/check-links#4]
RFE: Please add a check for this string in URLs: comparing-rhel-8-to-rhel-7 which is now an outdated title. 

Unrelated: I think it would be worthwhile to include the old staging URL parts: doc-stage.usersys and access.qa to the checks besides the new targets.

Thanks!

**Comment by jhradilek** [comment]
Thank you, Lenka! Implemented in commit 6af0fdbd.

The other requested functionality is already in, I implemented it along with the lb_target keywords.
